//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string text { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> rating { get; set; }
    }
}
