//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public string category { get; set; }
        public Nullable<int> cook_duration { get; set; }
        public Nullable<int> global_code { get; set; }
        public Nullable<int> company_id { get; set; }
    }
}
